#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

set -e

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake generate_secret_token
popd > /dev/null

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]; then
    echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

# Confirm database exists, if not create it
qry="select * from redmine.users;"
if ! /usr/bin/mysql -h "$OPENSHIFT_MYSQL_DB_HOST"              \
                    -u "$OPENSHIFT_MYSQL_DB_USERNAME"          \
                    --password="$OPENSHIFT_MYSQL_DB_PASSWORD"  \
                    "$OPENSHIFT_APP_NAME" -e "$qry" > /dev/null 2>&1; then
    echo
    echo "Schema not found! Recreating redmine schema"
    echo
    /usr/bin/mysql -h "$OPENSHIFT_MYSQL_DB_HOST"              \
                   -u "$OPENSHIFT_MYSQL_DB_USERNAME"          \
                   --password="$OPENSHIFT_MYSQL_DB_PASSWORD"  \
                   "$OPENSHIFT_APP_NAME" <<MYEOF
drop database if exists redmine;
create database redmine character set utf8;
MYEOF

    # Run db:migrate
    pushd ${OPENSHIFT_REPO_DIR} > /dev/null
    bundle exec "env RAILS_ENV='production' rake db:migrate"
    bundle exec "env RAILS_ENV='production' REDMINE_LANG='en' rake redmine:load_default_data"
    popd > /dev/null
    echo
    echo "done."
else
    echo "Database found, skipping import."
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}files ]
then
	mkdir ${OPENSHIFT_DATA_DIR}files
fi

ln -sf ${OPENSHIFT_DATA_DIR}files ${OPENSHIFT_REPO_DIR}files
