#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

set -e

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]; then
    echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

# Determinate wheather it is or it isn't the initial deployment,
# so the database will be created from redmine.sql or there are
# changes which need to be migrated.

if echo "use $OPENSHIFT_APP_NAME; show tables" | mysql  -h "$OPENSHIFT_MYSQL_DB_HOST" \
                                                        -P "$OPENSHIFT_MYSQL_DB_PORT" \
                                                        -u "$OPENSHIFT_MYSQL_DB_USERNAME" \
                                                        --password="$OPENSHIFT_MYSQL_DB_PASSWORD" | grep attachments > /dev/null
then
    # Runs on every other Redmine application deployment
    # except the first one.
    pushd ${OPENSHIFT_REPO_DIR} > /dev/null
    echo "Migrating database"
    bundle exec "env RAILS_ENV='production' rake db:migrate"
    popd > /dev/null
else
    # Runs on the inirtial Redmine deployment
    ###
    # If the quickstart is updated for newer version
    # redmine.sql needs to be updated too.

    pushd ${OPENSHIFT_REPO_DIR}/db > /dev/null
    echo "Loading database"
    gunzip redmine.sql.gz
    mysql   -h "$OPENSHIFT_MYSQL_DB_HOST" \
            -P "$OPENSHIFT_MYSQL_DB_PORT" \
            -u "$OPENSHIFT_MYSQL_DB_USERNAME" \
            --password="$OPENSHIFT_MYSQL_DB_PASSWORD" \
            "$OPENSHIFT_APP_NAME" < redmine.sql
    echo "Loading Redmine default configuration data"
    # bundle exec "env RAILS_ENV='production' REDMINE_LANG='en' rake redmine:load_default_data"
    popd > /dev/null
fi


if [ ! -d ${OPENSHIFT_DATA_DIR}files ]
then
	mkdir ${OPENSHIFT_DATA_DIR}files
fi

ln -sf ${OPENSHIFT_DATA_DIR}files ${OPENSHIFT_REPO_DIR}files
